# Generated by Django 2.2.3 on 2019-07-23 17:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(max_length=255)),
                ('kontak', models.CharField(max_length=20)),
                ('pendidikan', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
                ('kebangsaan', models.CharField(max_length=30)),
                ('perusahaan', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', tinymce.models.HTMLField()),
                ('tanggal', models.DateTimeField()),
                ('komentar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('testimoni', models.TextField(max_length=500)),
                ('foto_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pengalaman', models.CharField(max_length=255)),
                ('testimoni', models.TextField(max_length=500)),
                ('foto_url', models.CharField(max_length=100)),
            ],
        ),
    ]
