# Generated by Django 2.2.3 on 2019-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_selasa', '0002_auto_20190724_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
